name: Build and Test Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Cache Gradle Packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Install MariaDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-server mariadb-client

      - name: Start MariaDB Service
        run: |
          sudo systemctl start mariadb
          sudo mysql -u root -e "CREATE DATABASE virtual_wallet;"
          sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
          sudo mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS virtual_wallet;"

      - name: Build and Run Tests
        run: ./gradlew clean build --info
